from termcolor import colored, cprint
cprint("          / \ ", "cyan")
cprint("         /   \ ", "cyan")  
cprint("        /^.   \ ", "cyan")
cprint("       /  .-.  \ ", "cyan")
cprint("      /  (   ) _\ ", "cyan")
cprint("     / _.~   ~._^\ ", "cyan")
cprint("    /.^         ^.\ ", "cyan")
cprint("TermuxArch by Karataso", "cyan")
print("--------------------------------------------")
cprint("Instalacion finished", "green")
print("you may reboot Termux now")
print("Type exit below, or close the app entirely (Even the notification)")
print("after reboot you will automaticaly enter arch")
print("Ascii art is shown at arch startup, If yo wanna disable it, run the folowing command")
cprint("python ascci-removal.py", "yellow")
print("-----------------------------")
