from termcolor import cprint, colored
#asignamos todas las bariables, con color para poder dibujarlas despues
cprint("_  _ ____ ____ ____ ___ ____ ____ ____ ", "yellow")
cprint("|_/  |__| |__/ |__|  |  |__| [__  |  | ", "yellow")
cprint("| \_ |  | |  \ |  |  |  |  | ___] |__| ", "yellow")
Andr1 = colored("   ░█▀█░█▀█░░░█▀█░█▀█░█▀▄░█▀▄░█▀█░▀█▀░█▀▄", "green")
Andr2 = colored(" ░ █░█░█░█░░░█▀█░█░█░█░█░█▀▄░█░█░░█░░█░█", "green")
Andr3 = colored(" ░▀▀▀░▀░▀░░░▀░▀░▀░▀░▀▀░░▀░▀░▀▀▀░▀▀▀░▀▀░", "green")
logo01 = colored("                 ▄█▄             █████╗ ██████╗  ██████╗██╗  ██╗", "cyan")
logo02 = colored("                ▄███▄           ██╔══██╗██╔══██╗██╔════╝██║  ██║", "cyan")
logo03 = colored("               ▄█████▄          ███████║██████╔╝██║     ███████║", "cyan")
logo04 = colored("              ▄███████▄         ██╔══██║██╔══██╗██║     ██╔══██║", "cyan")
logo05 = colored("             ▄ ▀▀██████▄        ██║  ██║██║  ██║╚██████╗██║  ██║", "cyan")
logo06 = colored("            ▄██▄▄ ▀█████▄       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝", "cyan")
logo07 = colored("           ▄█████████████▄      ██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗", "cyan")
logo08 = colored("          ▄███████████████▄     ██║     ██║████╗  ██║██║   ██║╚██╗██╔╝", "cyan")
logo09 = colored("         ▄█████████████████▄    ██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝", "cyan")
logo10 = colored("        ▄███████████████████▄   ██║     ██║██║╚██╗██║██║   ██║ ██╔██╗", "cyan")
logo11 = colored("       ▄█████████▀▀▀▀████████▄  ███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗", "cyan")
logo12 = colored("      ▄████████▀      ▀███████▄ ╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝", "cyan")
logo13 = colored("     ▄█████████        ████▀▀██▄", "cyan")
logo14 = colored("    ▄██████████        ███████▄▄▄", "cyan")
logo15 = colored("   ▄██████████▀        ▀█████████▄", "cyan")
logo16 = colored("  ▄██████▀▀▀              ▀▀██████▄", "cyan")
logo17 = colored(" ▄███▀▀                       ▀▀███▄", "cyan")
logo18 = colored("▄▀▀                               ▀▀▄", "cyan")
#Momento de imprimir y ordenar las malditas variables
print(logo01)
print(logo02)
print(logo03)
print(logo04)
print(logo05)
print(logo06)
print(logo07)
print(logo08)
print(logo09)
print(logo10)
print(logo11)
print(logo12)
print(logo13)
print(logo14, Andr1)
print(logo15, Andr2)
print(logo16, Andr3)
print(logo17)
print(logo18)
print(logo19)
print(logo20)
print(logo21)
print("     ")
print("     ")
