from termcolor import cprint, colored
#asignamos todas las bariables, con color para poder dibujarlas despues
title01 = colored("             █████╗ ██████╗  ██████╗██╗  ██╗", "cyan")
title02 = colored("           ██╔══██╗██╔══██╗██╔════╝██║  ██║", "cyan")
title03 = colored("          ███████║██████╔╝██║     ███████║", "cyan")
title04 = colored("         ██╔══██║██╔══██╗██║     ██╔══██║", "cyan")
title05 = colored("        ██║  ██║██║  ██║╚██████╗██║  ██║", "cyan")
title06 = colored("       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝", "cyan")
title07 = colored("      ██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗", "cyan")
title08 = colored("     ██║     ██║████╗  ██║██║   ██║╚██╗██╔╝", "cyan")
title09 = colored("    ██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝", "cyan")
title10 = colored("   ██║     ██║██║╚██╗██║██║   ██║ ██╔██╗", "cyan")
title11 = colored("  ███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗", "cyan")
title12 = colored(" ╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝", "cyan")
logo01 = colored("                 ▄█▄", "cyan")
logo02 = colored("                ▄███▄", "cyan")
logo03 = colored("               ▄█████▄", "cyan")
logo04 = colored("              ▄███████▄", "cyan")
logo05 = colored("             ▄ ▀▀██████▄", "cyan")
logo06 = colored("            ▄██▄▄ ▀█████▄", "cyan")
logo07 = colored("           ▄█████████████▄", "cyan")
logo08 = colored("          ▄███████████████▄", "cyan")
logo09 = colored("         ▄█████████████████▄", "cyan")
logo10 = colored("        ▄███████████████████▄", "cyan")
logo11 = colored("       ▄█████████▀▀▀▀████████▄", "cyan")
logo12 = colored("      ▄████████▀      ▀███████▄", "cyan")
logo13 = colored("     ▄█████████        ████▀▀██▄", "cyan")
logo14 = colored("    ▄██████████        █████▄▄▄", "cyan")
logo15 = colored("   ▄██████████▀        ▀█████████▄", "cyan")
logo16 = colored("  ▄██████▀▀▀              ▀▀██████▄", "cyan")
logo17 = colored(" ▄███▀▀                       ▀▀███▄", "cyan")
logo18 = colored("▄▀▀                               ▀▀▄", "cyan")
logo19 = colored("░█▀█░█▀█░░░█▀█░█▀█░█▀▄░█▀▄░█▀█░▀█▀░█▀▄", "green")
logo20 = colored("░█░█░█░█░░░█▀█░█░█░█░█░█▀▄░█░█░░█░░█░█", "green")
logo21 = colored("░▀▀▀░▀░▀░░░▀░▀░▀░▀░▀▀░░▀░▀░▀▀▀░▀▀▀░▀▀░", "green")
#Momento de imprimir y ordenar las malditas variables
print(logo01, title01)
print(logo02, title02)
print(logo03, title03)
print(logo04, title04)
print(logo05, title05)
print(logo06, title06)
print(logo07, title07)
print(logo08, title08)
print(logo09, title09)
print(logo10, title10)
print(logo11, title11)
print(logo12, title12)
print(logo13)
print(logo14)
print(logo15)
print(logo16)
print(logo17)
print(logo18)
print(logo19)
print(logo20)
print(logo21)